# -*- coding: utf-8 -*-
"""5 Reccomendation system.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q7N3qCAz8PHJ0tuhPdKGbTRBwRibN0k0
"""

from fastai.collab import *
path = untar_data(URLs.ML_SAMPLE)
dls = CollabDataLoaders.from_csv(path/'ratings.csv') 
learn = collab_learner(dls, y_range=(0.5,5.5)) 
learn.fine_tune(10)

learn.show_results()